spring:
  data:
    mongodb:
      #host: 39.108.82.173
      #database: articledb
      #port: 27017
      #uri: mongodb://39.108.82.173:27017,39.108.82.173:27018,39.108.82.173:27019/articledb?connect=replicaSet&slaveOk=true&replicaSet=myrs
      uri: mongodb://39.108.82.173:27017,39.108.82.173:27117/articledb
  application:
    name: tenant-drool-fact
server:
  port: 8086
